%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\vasu\Desktop\datasets\U45_test\sheet.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 26-Apr-2022 12:13:59
l=routght(1);
%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 32,...
    'VariableNames',VariableNames,...
    'VariableTypes',VariableTypes,...
    'DataRange', "A1:AF1");

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A1:AF1";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ImportErrorRule = "error";

% Specify variable properties
opts = setvaropts(opts, ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32"], "TreatAsMissing", '');

% Import the data
sheet = readtable("C:\Users\vasu\Desktop\datasets\U45_test\sheet.xlsx", opts, "UseExcel", true);


%% Clear temporary variables
